// Get an access token from: https://gameon.nz/developer

@accessToken=eyJ0eXA...
@tournamentId=eb7ff3...

### GET User
GET http://localhost:5001/me
Authorization: Bearer {{accessToken}}

### GET User Photo
GET http://localhost:5001/me/photos?size=120x120
Authorization: Bearer {{accessToken}}

### POST User
POST http://localhost:5001/me
Authorization: Bearer {{accessToken}}




### POST Tournaments
POST http://localhost:5000/tournaments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Name1",
    "description": "Description1",
    "location": "Location1",
    "playingFor": "PlayingFor1"    
} 

### PUT Tournaments
PUT http://localhost:5000/tournaments/{{tournamentId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Name2",
    "description": "Description2",
    "location": "Location2",
    "playingFor": "PlayingFor2"    
} 

### GET Tournaments LOCAL
GET http://localhost:5000/tournaments
Authorization: Bearer {{accessToken}}

### DELETE Tournamnents LOCAL

DELETE http://localhost:5000/tournaments/{{tournamentId}}
Authorization: Bearer {{accessToken}}

### GET Tournament LOCAL
GET http://localhost:5000/tournaments/{{tournamentId}}
Authorization: Bearer {{accessToken}}


### Add Players to Tournament
POST http://localhost:5000/tournaments/{{tournamentId}}/players
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "playerIds": ["E4B9CCA...", "6411ACC8..."],
    "addMe": true
}

### GET Tournament Players 
GET http://localhost:5000/tournaments/{{tournamentId}}/players
Authorization: Bearer {{accessToken}}

### GET Tournament Player
GET http://localhost:5000/tournaments/{{tournamentId}}/players/E4B9CCAB54357895680E535E7DCB431EE73613FA91A10B5A8D87DE10A2588B86
Authorization: Bearer {{accessToken}}

### POST Tournament Results
POST http://localhost:5000/tournaments/{{tournamentId}}/results
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": "dc5991...",
    "player1Id": "E4B9CC...",
    "player2Id": "6411AC...",
    "winnerId": "6411AC..."
}

### GET Results for tournament 
GET http://localhost:5002/results/{{tournamentId}}?playerId=123
Authorization: Bearer {{accessToken}}