### GET Tournaments PROD
GET https://api.gameon.nz/tournaments/tenant1


### POST Tournament PROD
POST https://api.gameon.nz/tournaments/tenant1
Content-Type: application/json

{
    "name": "Name1",
    "description": "Description1",
    "location": "Location1",
    "playingFor": "PlayingFor1",
} 


### POST Tournaments LOCAL DEV
POST http://localhost:5000/tournaments/abcd1234
Content-Type: application/json

{
    "name": "Name1",
    "description": "Description1",
    "location": "Location1",
    "playingFor": "PlayingFor1"    
} 

### GET Tournaments LOCAL
GET http://localhost:5000/tournaments/abcd1234


### GET Tournament LOCAL
 GET http://localhost:5000/tournaments/abcd1234/abc1046

### Save Store
POST http://localhost:57766/v1.0/state/statestore
Content-Type: application/json

[{ "key": "key1", "value": "value1"}, { "key": "key2", "value": "value2"}]

### Get Store
GET http://localhost:57766/v1.0/state/statestore/abcd1234