apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: $(IdentityName)
spec:
  type: 0
  ResourceID: $(IdentityResourceId)
  ClientID: $(IdentityClientId)
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: $(IdentityName)-binding
spec:
  AzureIdentity: $(IdentityName)
  Selector: $(IdentityName)-selector
