apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameon-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - api.gameon.nz
    secretName: tls-secret
  rules:
  - host: api.gameon.nz
    http:
      paths:
      - path: /tournaments
        pathType: Prefix
        backend:
          service: 
            name: tournaments
            port:
              number: 80
      - path: /me
        pathType: Prefix
        backend:
          service: 
            name: users
            port: 
              number: 80
