### POST Tournament PROD
POST https://api.gameon.nz/tournaments/tenant1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1Q...

{
    "name": "Auckland Office - Table Tennis - Singles",
    "description": "Singles tournament 2020",
    "location": "The Hub on L6 Auckland",
    "playingFor": "Beers 🍻"
} 

### GET Tournament PROD
GET http://api.gameon.nz/tournaments/tenant1/849468128dd84962a2d4dd3b637367d7

### GET Tournaments PROD
GET https://api.gameon.nz/tournaments/tenant1
Authorization: Bearer eyJ0eXAiOiJKV1Q...

### POST Tournaments LOCAL DEV
POST http://localhost:5000/tournaments/abcd1234
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1Q...
{
    "name": "Name1",
    "description": "Description1",
    "location": "Location1",
    "playingFor": "PlayingFor1"    
} 

### GET Tournaments LOCAL
GET http://localhost:5000/tournaments/abcd1234
Authorization: Bearer eyJ0eXAiOiJKV1Q...


### GET Tournament LOCAL
 GET http://localhost:5000/tournaments/abcd1234/abc1046


### GET Health ASP.NET
GET https://localhost:44318/health
Authorization: Bearer eyJ0eXAiOiJKV1Q...

### Save Store
POST http://localhost:57766/v1.0/state/statestore
Content-Type: application/json

[{ "key": "key1", "value": "value1"}, { "key": "key2", "value": "value2"}]

### Get Store
GET http://localhost:57766/v1.0/state/statestore/abcd1234