name: Deploy Web App

on:
  push:
    branches: 
      - main
    paths:
      - "client/**"
  pull_request:
    branches: 
      - main
    paths:
      - "client/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log Level"
        required: true
        default: "verbose"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            cd ./deploy
            ./publish-web.ps1
