name: publish-webapp

on: 
  push:
    branches: [main]
    
jobs:
  build:

  #runs-on: ubuntu-latest

  steps:
  -  uses: actions/checkout@v2
       
  - name: Login to Azure
    uses: Azure/login@v1.1
    
  - name: Run publish-web.ps1
    uses: Azure/cli@1.0.4
