name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - "server/GameOn"
  pull_request:
    branches: [ main ]
    paths:
      - "server/GameOn"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'information'
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      working-directory: server/GameOn
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      working-directory: server/GameOn
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: server/GameOn
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: gameonaue 
        password: $ACR_PASSWORD 
        login-server: https://gameonaue.azurecr.io
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI Action
      uses: Azure/cli@1.0.4
      with:
        working-directory: server/GameOn/GameOn.Tournaments
        inlineScript: az acr build --registry gameonaue --image gameontournaments:latest .
